runtime: nodejs18  # Versi Node.js terbaru yang didukung

handlers:
  - url: /assets
    static_dir: dist/assets

  - url: /paper-bg.jpg
    static_files: gs://staging.my-project-413404.appspot.com/paper-bg.jpg
    upload: dist/paper-bg.jpg

  - url: /vite.svg
    static_files: gs://staging.my-project-413404.appspot.com/vite.svg
    upload: dist/vite.svg

  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
